### ISSUE TITLE
Compatibility of ECG detecting devices 

### ISSUE THREAD

**Issue by pchouse** [chickenjohn/ECG_Monitor_on_Android#1]
Is it possible for you t tell two or three example of ecg devices that is it possible to connect?

**Comment by chickenjohn** [comment]
The project is not able to directly connect to any ECG device. It connects with a Bluetooth serial port device and receive raw data from that.

**Comment by pchouse** [comment]
> 
> 
> The project is not able to directly connect to any ECG device. It connects with a Bluetooth serial port device and receive raw data from that.

Thanks. But connect with a device like this? 
https://www.alibaba.com/product-detail/Amazon-Mobile-EKG-Monitor-Captures-Heart_60755739240.html?spm=a2700.7724857.normalList.45.15696b2930CxfX

**Comment by chickenjohn** [comment]
It would need to figure out what kind of Bluetooth protocol such devices work with, then to alternate the bluetoothManager class to be compatible with the protocol. It might also be necessary to understand the detail of the data format of the device.
