### ISSUE TITLE
Explanation on data format being used

### ISSUE THREAD

**Issue by 512015** [chickenjohn/ECG_Monitor_on_Android#2]
Can you give me a paragraph or two of your ecg model data?I don't know what kind of data to send to bluetooth. Please！

**Comment by chickenjohn** [comment]
The [SendWaveTool](https://github.com/chickenjohn/ECG_Monitor_on_Android/tree/master/SendWaveTool) directory contains an example binary data file `leadii.bin` and a simple Python script to send it via Bluetooth Serial Port device. The binary file contains a portion of [MIT-BIH](https://physionet.org/physiobank/database/mitdb/) dataset.
