### ISSUE TITLE
wrong data range

### ISSUE THREAD

**Issue by amirart251** [chickenjohn/ECG_Monitor_on_Android#3]
ecg device return data range should between 0-1023...
i think this source return wrong value ...
arg1 hold return data from ecg device....

**Comment by chickenjohn** [comment]
I have no experience on developing this with real ECG device. As I said in the README, this app is just a "simple ECG waveform viewer" (and in fact you can regard this as a probe for any kind of timing sequence), and there's no plan to make it mature. 

Ideally a possible way of fixing "figures out of canvas" problem is to normalize the incoming data regarding to the height of the canvas.
